vich_uploader:
    db_driver: orm

    mappings:
        pieces_images:
            uri_prefix: /images/pieces
            upload_destination: '%kernel.project_dir%/public/images/pieces'


        user_documents:
            uri_prefix: /documents/user
            upload_destination: '%kernel.project_dir%/public/documents/user'
